# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectatedPassengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('on_passenger', models.IntegerField()),
                ('off_passenger', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RealPassengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('on_passenger', models.IntegerField()),
                ('off_passenger', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('station_name', models.CharField(max_length=16)),
                ('location_x', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_y', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='realpassengers',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Stations'),
        ),
        migrations.AddField(
            model_name='expectatedpassengers',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Stations'),
        ),
    ]
