# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpectatedPassengers',
            new_name='ExpectatedPassenger',
        ),
        migrations.RenameModel(
            old_name='RealPassengers',
            new_name='RealPassenger',
        ),
        migrations.RenameModel(
            old_name='Stations',
            new_name='Station',
        ),
    ]
