# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20170907_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ('station_name', 'code')},
        ),
    ]
