# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20170909_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expectatedpassenger',
            name='off_passenger',
        ),
        migrations.AddField(
            model_name='expectatedpassenger',
            name='off_passenger_1',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expectatedpassenger',
            name='off_passenger_2',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expectatedpassenger',
            name='off_passenger_3',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realpassenger',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
